hello: from the params file

users:
  - Luke
  - Leia
  - Han
  - Chewbacca
  - R2D2

clouds:
  - aws
  - gcp
k8s_versions:
  - "1.32"
  - "1.33"

envs:
  - cloud: gcp
    k8s_version: "1.32"
  - cloud: gcp
    k8s_version: "1.33"
  - cloud: aws
    k8s_version: "1.32"
  - cloud: aws
    k8s_version: "1.33"
