platform: linux

image_resource:
  type: mock
  source:
    mirror_self: true

inputs:
  - name: repo

outputs:
  - name: repo

params:
  GIT_AUTHOR:
run:
  path: bash
  args:
    - -c
    - |
      set -euo pipefail

      apk add -q --no-progress git
      git config --global user.name "Concourse-CI"
      git config --global user.email "ci@example.com"

      cd repo

      today="$(date +%Y-%m-%d)"
      echo "$today" > todays-date

      git add ./todays-date
      git commit -m "Add todays date"


